const styles = {
  wrapper: {
    fontFamily: "'Segoe UI', sans-serif",
    maxWidth: '1520px',
    
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontWeight: 700,
    fontSize: '16px',
    color: '#3658BF',
  },
  saveBtn: {
    background: '#3658BF',
    color: 'white',
    border: 'none',
    padding: '8px 16px',
    fontSize: '18px',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  formLayout: {
    display: 'flex',
    gap: '16px',
  },
  formMain: {
    flex: 1,
    background: 'white',
    borderRadius: '10px',
    boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
    maxWidth: '860px',
    width: '100%',
  },
  title: {
    fontSize: '24px',
    fontWeight: 700,
    height: '60px',
    borderBottom: '1px solid #D4DAED',
    display: 'flex',
    alignItems: 'center',
    padding: '0 24px',
  },
  tagGroup: {
    display: 'flex',
    gap: '8px',
    marginTop: '8px',
  },
  tag: {
    background: '#3658BF',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '16px',
    fontSize: '12px',
  },
  drawer: {
    width: '320px',
    background: 'white',
  },
  drawerHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 24px',
    height: '60px',
    borderBottom: '1px solid #D4DAED',
  },
  drawerBody: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    borderBottom: '1px solid #D4DAED',
    borderTop: '1px solid #D4DAED',
    marginTop: '8px',
    padding: '16px 24px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '16px',
  },
  formLabel: {
    marginBottom: '4px',
    fontSize: '14px',
    fontWeight: 400,
    color: '#797979',
  },
  input: {
    borderRadius: '5px',
    fontSize: '14px',
    outline: 'none',
    border: '1px solid #ccc',
    padding: '0 10px',
    height: '27px',
    
  },
  textarea: {
    borderRadius: '5px',
    fontSize: '14px',
    outline: 'none',
    border: '1px solid #ccc',
    padding: '10px',
    resize: 'vertical',
    height: '93px',
  },
  btnGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    textAlign: 'center',
    padding: '16px 24px',
  },
  addMoreBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #3658BF',
    background: 'white',
    color: '#3658BF',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    height: '28px',
    width: '209px',
    fontWeight: 700,
  },
  saveButton: {
    padding: '8px 20px',
    background: '#3658BF',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontWeight: 500,
    cursor: 'pointer',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
};

export default styles;
